### ISSUE TITLE
Datetime get_loc error

### ISSUE THREAD

**Issue by janvandinther** [adambgnr/daypym#4]
Traceback (most recent call last):
  File "c:/UserData/z0045c5j/Documents/Pilots/Vopak/daypym/example_workflow/visual_workflow.py", line 26, in <module>
    ill=ill.loc[t, : ], save_fig=False)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 805, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 929, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 3737, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py", line 1039, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "C:\Users\z0045c5j\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 410, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas\_libs\index.pyx", line 440, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2001-06-06 15:10:00')

**Comment by adambgnr** [comment]
Hi @janvandinther 

You can find my attempt for a solution at: 
https://gitlab.tue.nl/bp-tue/daypym/issues/1

Please note that Daypym was moved from GutHub to GitLab in 2019. Please use the GitLab page to open new issues.
